### ISSUE TITLE
Debug output possible?

### ISSUE THREAD

**Issue by gear4dave** [jerrywithaz/google-datastore-emulator-ui#2]
Hi - is there any way of running this with any level of debug output?

I've got it up and running just fine, but it's rendering just a blank page without any UI elements, etc:

![image](https://user-images.githubusercontent.com/12171117/150396412-a907db99-3598-471e-a43f-2eb210e628b7.png)

Looks like a great project, something that I've been begging Google for, for a long time!

**Comment by jerrywithaz** [comment]
Hey there @gear4dave not at the moment! I am actually doing some updates to the project today and will be releasing and I can add some debug functionality to it. However, in the mean time:

1. What is your datastore emulator url at the moment? such as `http://localhost:8097`
2. What command did you use to run? such as `google-datastore-emulator-ui -i my-project -e http://localhost:8097
`

**Comment by gear4dave** [comment]
> Hey there @gear4dave not at the moment! I am actually doing some updates to the project today and will be releasing and I can add some debug functionality to it. However, in the mean time:
> 
> 1. What is your datastore emulator url at the moment? such as `http://localhost:8097`
> 2. What command did you use to run? such as `google-datastore-emulator-ui -i my-project -e http://localhost:8097 `

Hi, thanks for the quick response.

Here is the output from everything running:

```
$> sudo google-datastore-emulator-ui -i proj-dev -e http://127.0.0.1:8090
💯 Updating client server config at:  /usr/local/lib/node_modules/google-datastore-emulator-ui/src/client/build/server_config.json { port: 8002 }
✅ PROJECT_ID proj-dev
✅ DATASTORE_EMULATOR_HOST https://127.0.0.1:8090
🚀 Server ready at http://localhost:8002/graphql
INFO: Accepting connections at http://localhost:3000
```

Does it matter than this is running under sudo? It's pretty much the only way I could get it to run, as my non-root user doesn't have the required permissions to write to certain directories required by the UI.

**Comment by jerrywithaz** [comment]
Hmm...I see 2 possible issues:

1. I have not tested this library with using the ip address of localhost `127.0.0.1`. You can try changing it to `http://localhost:8090` and see if that works.
2. Also, it looks like the `DATASTORE_EMULATOR_HOST` environment variable is somehow https, which I have also not tested as well. That might be a result of the localhost ip address.

In addition, I've release an updated version of this library that adds more features like backup imports/exports and debug info, release notes here: https://github.com/jerrywithaz/google-datastore-emulator-ui/releases/tag/v1.3.1

**Comment by jerrywithaz** [comment]
I don't think sudo should be an issue but I will have to confirm that's the case

**Comment by gear4dave** [comment]
I've tried using 127.0.0.1 and localhost, and http vs https - none seem to make any difference. I've also set a few directory permissions and run as a normal user, again with the same results. I don't think there is anything particularly special about my datastore emulator or the data contained therein.

**Comment by jerrywithaz** [comment]
Can you try the latest version and see if some of the UI debug output helps?

**Comment by gear4dave** [comment]
It looks like there might be a path mismatch perhaps? With running the --dev param, this is the output:

```
sudo google-datastore-emulator-ui -i cas-dev -e http://localhost:8090 --dev
💯 Updating client server config at:  /usr/local/lib/node_modules/google-datastore-emulator-ui/src/client/public/server_config.json { port: 8002 }
(node:218864) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open '/usr/local/lib/node_modules/google-datastore-emulator-ui/src/client/public/server_config.json'
    at Object.openSync (fs.js:462:3)
    at Object.writeFileSync (fs.js:1384:35)
    at outputServerConfigToClient (/usr/local/lib/node_modules/google-datastore-emulator-ui/lib/index.js:76:8)
    at /usr/local/lib/node_modules/google-datastore-emulator-ui/lib/index.js:150:21
    at step (/usr/local/lib/node_modules/google-datastore-emulator-ui/lib/index.js:53:23)
    at Object.next (/usr/local/lib/node_modules/google-datastore-emulator-ui/lib/index.js:34:53)
    at fulfilled (/usr/local/lib/node_modules/google-datastore-emulator-ui/lib/index.js:25:58)
```

Once I'd copied this file from /public to /build, the app then fails to launch, with the following output:

```
npm
npm ERR! code ENOENT
npm ERR! syscall open
npm ERR! path /home/gear4dave/package.json
npm ERR! errno -2

 ERR! code ENOENT
npm ERR! syscall open
npm ERR! path /home/gear4dave/package.json
npm ERR! errno -2

npm ERR! enoent ENOENT: no such file or directory, open '/home/gear4dave/package.json'

npm ERR! enoent ENOENT: no such file or directory, open '/home/gear4dave/package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 




npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2022-01-24T09_08_19_955Z-debug.log

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2022-01-24T09_08_19_955Z-debug.log
```

I haven't tried touching this file yet - unsure if there is something required to be in it.
